namespace FreelancerApp
{
    partial class Login
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Login));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.RegisterButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.usernameTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LoginButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.PasswordTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.showpasswordCheckBox = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.bunifuFormControlBox1 = new Bunifu.UI.WinForms.BunifuFormControlBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.ShowPassCheckBox = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.PasswordTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = false;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = true;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = false;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("MV Boli", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(274, 125);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(75, 31);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "Log in";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel1.Click += new System.EventHandler(this.bunifuLabel1_Click);
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(31)))), ((int)(((byte)(74)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.RegisterButton);
            this.bunifuPanel1.Controls.Add(this.bunifuButton1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 374);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(636, 55);
            this.bunifuPanel1.TabIndex = 2;
            // 
            // RegisterButton
            // 
            this.RegisterButton.AllowAnimations = true;
            this.RegisterButton.AllowMouseEffects = true;
            this.RegisterButton.AllowToggling = false;
            this.RegisterButton.AnimationSpeed = 200;
            this.RegisterButton.AutoGenerateColors = false;
            this.RegisterButton.AutoRoundBorders = false;
            this.RegisterButton.AutoSizeLeftIcon = true;
            this.RegisterButton.AutoSizeRightIcon = true;
            this.RegisterButton.BackColor = System.Drawing.Color.Transparent;
            this.RegisterButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.RegisterButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("RegisterButton.BackgroundImage")));
            this.RegisterButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegisterButton.ButtonText = "Create Account";
            this.RegisterButton.ButtonTextMarginLeft = 0;
            this.RegisterButton.ColorContrastOnClick = 45;
            this.RegisterButton.ColorContrastOnHover = 45;
            this.RegisterButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.RegisterButton.CustomizableEdges = borderEdges5;
            this.RegisterButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.RegisterButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RegisterButton.DisabledFillColor = System.Drawing.Color.Empty;
            this.RegisterButton.DisabledForecolor = System.Drawing.Color.Empty;
            this.RegisterButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.RegisterButton.Font = new System.Drawing.Font("Segoe UI Black", 12F, System.Drawing.FontStyle.Bold);
            this.RegisterButton.ForeColor = System.Drawing.Color.White;
            this.RegisterButton.IconLeft = null;
            this.RegisterButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.RegisterButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.RegisterButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.RegisterButton.IconMarginLeft = 11;
            this.RegisterButton.IconPadding = 10;
            this.RegisterButton.IconRight = null;
            this.RegisterButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.RegisterButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.RegisterButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.RegisterButton.IconSize = 25;
            this.RegisterButton.IdleBorderColor = System.Drawing.Color.Empty;
            this.RegisterButton.IdleBorderRadius = 0;
            this.RegisterButton.IdleBorderThickness = 0;
            this.RegisterButton.IdleFillColor = System.Drawing.Color.Empty;
            this.RegisterButton.IdleIconLeftImage = null;
            this.RegisterButton.IdleIconRightImage = null;
            this.RegisterButton.IndicateFocus = false;
            this.RegisterButton.Location = new System.Drawing.Point(185, 12);
            this.RegisterButton.Name = "RegisterButton";
            this.RegisterButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RegisterButton.OnDisabledState.BorderRadius = 15;
            this.RegisterButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegisterButton.OnDisabledState.BorderThickness = 1;
            this.RegisterButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RegisterButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RegisterButton.OnDisabledState.IconLeftImage = null;
            this.RegisterButton.OnDisabledState.IconRightImage = null;
            this.RegisterButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.RegisterButton.onHoverState.BorderRadius = 15;
            this.RegisterButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegisterButton.onHoverState.BorderThickness = 1;
            this.RegisterButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(62)))), ((int)(((byte)(120)))));
            this.RegisterButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.RegisterButton.onHoverState.IconLeftImage = null;
            this.RegisterButton.onHoverState.IconRightImage = null;
            this.RegisterButton.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.RegisterButton.OnIdleState.BorderRadius = 15;
            this.RegisterButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegisterButton.OnIdleState.BorderThickness = 1;
            this.RegisterButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(183)))), ((int)(((byte)(42)))));
            this.RegisterButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.RegisterButton.OnIdleState.IconLeftImage = null;
            this.RegisterButton.OnIdleState.IconRightImage = null;
            this.RegisterButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RegisterButton.OnPressedState.BorderRadius = 15;
            this.RegisterButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegisterButton.OnPressedState.BorderThickness = 1;
            this.RegisterButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RegisterButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.RegisterButton.OnPressedState.IconLeftImage = null;
            this.RegisterButton.OnPressedState.IconRightImage = null;
            this.RegisterButton.Size = new System.Drawing.Size(233, 40);
            this.RegisterButton.TabIndex = 8;
            this.RegisterButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.RegisterButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.RegisterButton.TextMarginLeft = 0;
            this.RegisterButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.RegisterButton.UseDefaultRadiusAndThickness = true;
            this.RegisterButton.Click += new System.EventHandler(this.RegisterButton_Click);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = true;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Register";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges6;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeft = null;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRight = null;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleBorderRadius = 0;
            this.bunifuButton1.IdleBorderThickness = 0;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(507, 216);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 31;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 31;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(62)))), ((int)(((byte)(120)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnIdleState.BorderRadius = 31;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 31;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(91, 31);
            this.bunifuButton1.TabIndex = 4;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // usernameTextBox
            // 
            this.usernameTextBox.AcceptsReturn = false;
            this.usernameTextBox.AcceptsTab = false;
            this.usernameTextBox.AnimationSpeed = 200;
            this.usernameTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.usernameTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.usernameTextBox.AutoSizeHeight = true;
            this.usernameTextBox.BackColor = System.Drawing.Color.Transparent;
            this.usernameTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("usernameTextBox.BackgroundImage")));
            this.usernameTextBox.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.usernameTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.usernameTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.usernameTextBox.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            this.usernameTextBox.BorderRadius = 15;
            this.usernameTextBox.BorderThickness = 1;
            this.usernameTextBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.usernameTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.usernameTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.usernameTextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.usernameTextBox.DefaultText = "";
            this.usernameTextBox.FillColor = System.Drawing.Color.White;
            this.usernameTextBox.HideSelection = true;
            this.usernameTextBox.IconLeft = null;
            this.usernameTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.usernameTextBox.IconPadding = 10;
            this.usernameTextBox.IconRight = null;
            this.usernameTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.usernameTextBox.Lines = new string[0];
            this.usernameTextBox.Location = new System.Drawing.Point(140, 174);
            this.usernameTextBox.MaxLength = 32767;
            this.usernameTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.usernameTextBox.Modified = false;
            this.usernameTextBox.Multiline = false;
            this.usernameTextBox.Name = "usernameTextBox";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.usernameTextBox.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.usernameTextBox.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.usernameTextBox.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.usernameTextBox.OnIdleState = stateProperties24;
            this.usernameTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.usernameTextBox.PasswordChar = '\0';
            this.usernameTextBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(31)))), ((int)(((byte)(74)))));
            this.usernameTextBox.PlaceholderText = "Enter your Username";
            this.usernameTextBox.ReadOnly = false;
            this.usernameTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.usernameTextBox.SelectedText = "";
            this.usernameTextBox.SelectionLength = 0;
            this.usernameTextBox.SelectionStart = 0;
            this.usernameTextBox.ShortcutsEnabled = true;
            this.usernameTextBox.Size = new System.Drawing.Size(341, 39);
            this.usernameTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.usernameTextBox.TabIndex = 3;
            this.usernameTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.usernameTextBox.TextMarginBottom = 0;
            this.usernameTextBox.TextMarginLeft = 3;
            this.usernameTextBox.TextMarginTop = 1;
            this.usernameTextBox.TextPlaceholder = "Enter your Username";
            this.usernameTextBox.UseSystemPasswordChar = false;
            this.usernameTextBox.WordWrap = true;
            // 
            // LoginButton
            // 
            this.LoginButton.AllowAnimations = true;
            this.LoginButton.AllowMouseEffects = true;
            this.LoginButton.AllowToggling = false;
            this.LoginButton.AnimationSpeed = 200;
            this.LoginButton.AutoGenerateColors = false;
            this.LoginButton.AutoRoundBorders = false;
            this.LoginButton.AutoSizeLeftIcon = true;
            this.LoginButton.AutoSizeRightIcon = true;
            this.LoginButton.BackColor = System.Drawing.Color.Transparent;
            this.LoginButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.LoginButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("LoginButton.BackgroundImage")));
            this.LoginButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LoginButton.ButtonText = "Log In";
            this.LoginButton.ButtonTextMarginLeft = 0;
            this.LoginButton.ColorContrastOnClick = 45;
            this.LoginButton.ColorContrastOnHover = 45;
            this.LoginButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.LoginButton.CustomizableEdges = borderEdges4;
            this.LoginButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.LoginButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LoginButton.DisabledFillColor = System.Drawing.Color.Empty;
            this.LoginButton.DisabledForecolor = System.Drawing.Color.Empty;
            this.LoginButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.LoginButton.Font = new System.Drawing.Font("Segoe UI Black", 12.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.LoginButton.ForeColor = System.Drawing.Color.White;
            this.LoginButton.IconLeft = null;
            this.LoginButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.LoginButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.LoginButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.LoginButton.IconMarginLeft = 11;
            this.LoginButton.IconPadding = 10;
            this.LoginButton.IconRight = null;
            this.LoginButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.LoginButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.LoginButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.LoginButton.IconSize = 25;
            this.LoginButton.IdleBorderColor = System.Drawing.Color.Empty;
            this.LoginButton.IdleBorderRadius = 0;
            this.LoginButton.IdleBorderThickness = 0;
            this.LoginButton.IdleFillColor = System.Drawing.Color.Empty;
            this.LoginButton.IdleIconLeftImage = null;
            this.LoginButton.IdleIconRightImage = null;
            this.LoginButton.IndicateFocus = false;
            this.LoginButton.Location = new System.Drawing.Point(140, 312);
            this.LoginButton.Name = "LoginButton";
            this.LoginButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LoginButton.OnDisabledState.BorderRadius = 15;
            this.LoginButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LoginButton.OnDisabledState.BorderThickness = 1;
            this.LoginButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.LoginButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.LoginButton.OnDisabledState.IconLeftImage = null;
            this.LoginButton.OnDisabledState.IconRightImage = null;
            this.LoginButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.LoginButton.onHoverState.BorderRadius = 15;
            this.LoginButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LoginButton.onHoverState.BorderThickness = 1;
            this.LoginButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(62)))), ((int)(((byte)(120)))));
            this.LoginButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.LoginButton.onHoverState.IconLeftImage = null;
            this.LoginButton.onHoverState.IconRightImage = null;
            this.LoginButton.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.LoginButton.OnIdleState.BorderRadius = 15;
            this.LoginButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LoginButton.OnIdleState.BorderThickness = 1;
            this.LoginButton.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.LoginButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.LoginButton.OnIdleState.IconLeftImage = null;
            this.LoginButton.OnIdleState.IconRightImage = null;
            this.LoginButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.LoginButton.OnPressedState.BorderRadius = 15;
            this.LoginButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LoginButton.OnPressedState.BorderThickness = 1;
            this.LoginButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.LoginButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.LoginButton.OnPressedState.IconLeftImage = null;
            this.LoginButton.OnPressedState.IconRightImage = null;
            this.LoginButton.Size = new System.Drawing.Size(341, 46);
            this.LoginButton.TabIndex = 5;
            this.LoginButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LoginButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.LoginButton.TextMarginLeft = 0;
            this.LoginButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.LoginButton.UseDefaultRadiusAndThickness = true;
            this.LoginButton.Click += new System.EventHandler(this.LoginButton_Click);
            // 
            // PasswordTextBox
            // 
            this.PasswordTextBox.AcceptsReturn = false;
            this.PasswordTextBox.AcceptsTab = false;
            this.PasswordTextBox.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.PasswordTextBox.AnimationSpeed = 200;
            this.PasswordTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PasswordTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PasswordTextBox.AutoSizeHeight = true;
            this.PasswordTextBox.BackColor = System.Drawing.Color.Transparent;
            this.PasswordTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PasswordTextBox.BackgroundImage")));
            this.PasswordTextBox.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.PasswordTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PasswordTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.PasswordTextBox.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            this.PasswordTextBox.BorderRadius = 15;
            this.PasswordTextBox.BorderThickness = 1;
            this.PasswordTextBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.PasswordTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PasswordTextBox.Cursor = System.Windows.Forms.Cursors.Default;
            this.PasswordTextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.PasswordTextBox.DefaultText = "";
            this.PasswordTextBox.FillColor = System.Drawing.Color.White;
            this.PasswordTextBox.HideSelection = true;
            this.PasswordTextBox.IconLeft = null;
            this.PasswordTextBox.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.PasswordTextBox.IconPadding = 10;
            this.PasswordTextBox.IconRight = null;
            this.PasswordTextBox.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.PasswordTextBox.Lines = new string[0];
            this.PasswordTextBox.Location = new System.Drawing.Point(32736, 32690);
            this.PasswordTextBox.MaxLength = 32767;
            this.PasswordTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.PasswordTextBox.Modified = false;
            this.PasswordTextBox.Multiline = false;
            this.PasswordTextBox.Name = "PasswordTextBox";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordTextBox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.PasswordTextBox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordTextBox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordTextBox.OnIdleState = stateProperties20;
            this.PasswordTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.PasswordTextBox.PasswordChar = '\0';
            this.PasswordTextBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(31)))), ((int)(((byte)(74)))));
            this.PasswordTextBox.PlaceholderText = "Enter your Password";
            this.PasswordTextBox.ReadOnly = false;
            this.PasswordTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PasswordTextBox.SelectedText = "";
            this.PasswordTextBox.SelectionLength = 0;
            this.PasswordTextBox.SelectionStart = 0;
            this.PasswordTextBox.ShortcutsEnabled = true;
            this.PasswordTextBox.Size = new System.Drawing.Size(341, 39);
            this.PasswordTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.PasswordTextBox.TabIndex = 6;
            this.PasswordTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PasswordTextBox.TextMarginBottom = 0;
            this.PasswordTextBox.TextMarginLeft = 3;
            this.PasswordTextBox.TextMarginTop = 1;
            this.PasswordTextBox.TextPlaceholder = "Enter your Password";
            this.PasswordTextBox.UseSystemPasswordChar = true;
            this.PasswordTextBox.WordWrap = true;
            // 
            // showpasswordCheckBox
            // 
            this.showpasswordCheckBox.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.showpasswordCheckBox.AllowBindingControlAnimation = true;
            this.showpasswordCheckBox.AllowBindingControlColorChanges = false;
            this.showpasswordCheckBox.AllowBindingControlLocation = true;
            this.showpasswordCheckBox.AllowCheckBoxAnimation = true;
            this.showpasswordCheckBox.AllowCheckmarkAnimation = true;
            this.showpasswordCheckBox.AllowOnHoverStates = true;
            this.showpasswordCheckBox.AutoCheck = true;
            this.showpasswordCheckBox.BackColor = System.Drawing.Color.Transparent;
            this.showpasswordCheckBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("showpasswordCheckBox.BackgroundImage")));
            this.showpasswordCheckBox.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.showpasswordCheckBox.BindingControl = this.PasswordTextBox;
            this.showpasswordCheckBox.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.showpasswordCheckBox.BorderRadius = 10;
            this.showpasswordCheckBox.Checked = false;
            this.showpasswordCheckBox.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Unchecked;
            this.showpasswordCheckBox.Cursor = System.Windows.Forms.Cursors.Default;
            this.showpasswordCheckBox.CustomCheckmarkImage = null;
            this.showpasswordCheckBox.Location = new System.Drawing.Point(32736, 32690);
            this.showpasswordCheckBox.MinimumSize = new System.Drawing.Size(17, 17);
            this.showpasswordCheckBox.Name = "showpasswordCheckBox";
            this.showpasswordCheckBox.OnCheck.BorderColor = System.Drawing.Color.DodgerBlue;
            this.showpasswordCheckBox.OnCheck.BorderRadius = 10;
            this.showpasswordCheckBox.OnCheck.BorderThickness = 2;
            this.showpasswordCheckBox.OnCheck.CheckBoxColor = System.Drawing.Color.DodgerBlue;
            this.showpasswordCheckBox.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.showpasswordCheckBox.OnCheck.CheckmarkThickness = 2;
            this.showpasswordCheckBox.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.showpasswordCheckBox.OnDisable.BorderRadius = 10;
            this.showpasswordCheckBox.OnDisable.BorderThickness = 2;
            this.showpasswordCheckBox.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.showpasswordCheckBox.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.showpasswordCheckBox.OnDisable.CheckmarkThickness = 2;
            this.showpasswordCheckBox.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.showpasswordCheckBox.OnHoverChecked.BorderRadius = 10;
            this.showpasswordCheckBox.OnHoverChecked.BorderThickness = 2;
            this.showpasswordCheckBox.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.showpasswordCheckBox.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.showpasswordCheckBox.OnHoverChecked.CheckmarkThickness = 2;
            this.showpasswordCheckBox.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.showpasswordCheckBox.OnHoverUnchecked.BorderRadius = 10;
            this.showpasswordCheckBox.OnHoverUnchecked.BorderThickness = 1;
            this.showpasswordCheckBox.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.showpasswordCheckBox.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.showpasswordCheckBox.OnUncheck.BorderRadius = 10;
            this.showpasswordCheckBox.OnUncheck.BorderThickness = 1;
            this.showpasswordCheckBox.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.showpasswordCheckBox.Size = new System.Drawing.Size(21, 21);
            this.showpasswordCheckBox.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.showpasswordCheckBox.TabIndex = 7;
            this.showpasswordCheckBox.ThreeState = false;
            this.showpasswordCheckBox.ToolTipText = null;
            this.showpasswordCheckBox.CheckedChanged += new System.EventHandler<Bunifu.UI.WinForms.BunifuCheckBox.CheckedChangedEventArgs>(this.showpasswordCheckBox_CheckedChanged);
            // 
            // bunifuFormControlBox1
            // 
            this.bunifuFormControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuFormControlBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(23)))), ((int)(((byte)(62)))));
            this.bunifuFormControlBox1.BunifuFormDrag = null;
            this.bunifuFormControlBox1.CloseBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.CloseBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.CloseBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.CloseBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.CloseBoxOptions.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.CloseBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.CloseBoxOptions.Icon")));
            this.bunifuFormControlBox1.CloseBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.CloseBoxOptions.IconColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.CloseBoxOptions.IconHoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.CloseBoxOptions.IconPressedColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.CloseBoxOptions.IconSize = new System.Drawing.Size(18, 18);
            this.bunifuFormControlBox1.CloseBoxOptions.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.HelpBox = false;
            this.bunifuFormControlBox1.HelpBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.HelpBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.HelpBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.HelpBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.HelpBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.HelpBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.HelpBoxOptions.Icon")));
            this.bunifuFormControlBox1.HelpBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.HelpBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconSize = new System.Drawing.Size(22, 22);
            this.bunifuFormControlBox1.HelpBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Location = new System.Drawing.Point(531, 2);
            this.bunifuFormControlBox1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuFormControlBox1.MaximizeBox = false;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconAlt = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.IconAlt")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconSize = new System.Drawing.Size(16, 16);
            this.bunifuFormControlBox1.MaximizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.MinimizeBox = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MinimizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconHoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconPressedColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconSize = new System.Drawing.Size(14, 14);
            this.bunifuFormControlBox1.MinimizeBoxOptions.PressedColor = System.Drawing.Color.DarkGray;
            this.bunifuFormControlBox1.Name = "bunifuFormControlBox1";
            this.bunifuFormControlBox1.ShowDesignBorders = false;
            this.bunifuFormControlBox1.Size = new System.Drawing.Size(105, 37);
            this.bunifuFormControlBox1.TabIndex = 11;
            this.bunifuFormControlBox1.HelpClicked += new System.EventHandler(this.bunifuFormControlBox1_HelpClicked);
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.AutoSize = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Baskerville Old Face", 26.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel4.Location = new System.Drawing.Point(235, 77);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(166, 52);
            this.bunifuLabel4.TabIndex = 19;
            this.bunifuLabel4.Text = "Freelancer";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = false;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(299, 2);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(79, 79);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 27;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // ShowPassCheckBox
            // 
            this.ShowPassCheckBox.AllowBindingControlAnimation = false;
            this.ShowPassCheckBox.AllowBindingControlColorChanges = false;
            this.ShowPassCheckBox.AllowBindingControlLocation = false;
            this.ShowPassCheckBox.AllowCheckBoxAnimation = false;
            this.ShowPassCheckBox.AllowCheckmarkAnimation = false;
            this.ShowPassCheckBox.AllowOnHoverStates = false;
            this.ShowPassCheckBox.AutoCheck = true;
            this.ShowPassCheckBox.BackColor = System.Drawing.Color.Transparent;
            this.ShowPassCheckBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ShowPassCheckBox.BackgroundImage")));
            this.ShowPassCheckBox.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.ShowPassCheckBox.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.ShowPassCheckBox.BorderRadius = 12;
            this.ShowPassCheckBox.Checked = false;
            this.ShowPassCheckBox.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Indeterminate;
            this.ShowPassCheckBox.Cursor = System.Windows.Forms.Cursors.Default;
            this.ShowPassCheckBox.CustomCheckmarkImage = null;
            this.ShowPassCheckBox.Location = new System.Drawing.Point(488, 265);
            this.ShowPassCheckBox.MinimumSize = new System.Drawing.Size(17, 17);
            this.ShowPassCheckBox.Name = "ShowPassCheckBox";
            this.ShowPassCheckBox.OnCheck.BorderColor = System.Drawing.Color.DodgerBlue;
            this.ShowPassCheckBox.OnCheck.BorderRadius = 12;
            this.ShowPassCheckBox.OnCheck.BorderThickness = 2;
            this.ShowPassCheckBox.OnCheck.CheckBoxColor = System.Drawing.Color.DodgerBlue;
            this.ShowPassCheckBox.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.ShowPassCheckBox.OnCheck.CheckmarkThickness = 2;
            this.ShowPassCheckBox.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.ShowPassCheckBox.OnDisable.BorderRadius = 12;
            this.ShowPassCheckBox.OnDisable.BorderThickness = 2;
            this.ShowPassCheckBox.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.ShowPassCheckBox.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.ShowPassCheckBox.OnDisable.CheckmarkThickness = 2;
            this.ShowPassCheckBox.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ShowPassCheckBox.OnHoverChecked.BorderRadius = 12;
            this.ShowPassCheckBox.OnHoverChecked.BorderThickness = 2;
            this.ShowPassCheckBox.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ShowPassCheckBox.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.ShowPassCheckBox.OnHoverChecked.CheckmarkThickness = 2;
            this.ShowPassCheckBox.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ShowPassCheckBox.OnHoverUnchecked.BorderRadius = 12;
            this.ShowPassCheckBox.OnHoverUnchecked.BorderThickness = 1;
            this.ShowPassCheckBox.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.ShowPassCheckBox.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.ShowPassCheckBox.OnUncheck.BorderRadius = 12;
            this.ShowPassCheckBox.OnUncheck.BorderThickness = 1;
            this.ShowPassCheckBox.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.ShowPassCheckBox.Size = new System.Drawing.Size(21, 21);
            this.ShowPassCheckBox.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Flat;
            this.ShowPassCheckBox.TabIndex = 28;
            this.ShowPassCheckBox.ThreeState = false;
            this.ShowPassCheckBox.ToolTipText = null;
            this.ShowPassCheckBox.CheckedChanged += new System.EventHandler<Bunifu.UI.WinForms.BunifuCheckBox.CheckedChangedEventArgs>(this.ShowPassCheckBox_CheckedChanged);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(516, 271);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(82, 15);
            this.bunifuLabel2.TabIndex = 29;
            this.bunifuLabel2.Text = "Show Password";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // PasswordTextBox1
            // 
            this.PasswordTextBox1.AcceptsReturn = false;
            this.PasswordTextBox1.AcceptsTab = false;
            this.PasswordTextBox1.AnimationSpeed = 200;
            this.PasswordTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PasswordTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PasswordTextBox1.AutoSizeHeight = true;
            this.PasswordTextBox1.BackColor = System.Drawing.Color.Transparent;
            this.PasswordTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PasswordTextBox1.BackgroundImage")));
            this.PasswordTextBox1.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.PasswordTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PasswordTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.PasswordTextBox1.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            this.PasswordTextBox1.BorderRadius = 15;
            this.PasswordTextBox1.BorderThickness = 1;
            this.PasswordTextBox1.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.PasswordTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PasswordTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PasswordTextBox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.PasswordTextBox1.DefaultText = "";
            this.PasswordTextBox1.FillColor = System.Drawing.Color.White;
            this.PasswordTextBox1.HideSelection = true;
            this.PasswordTextBox1.IconLeft = null;
            this.PasswordTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.PasswordTextBox1.IconPadding = 10;
            this.PasswordTextBox1.IconRight = null;
            this.PasswordTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.PasswordTextBox1.Lines = new string[0];
            this.PasswordTextBox1.Location = new System.Drawing.Point(140, 247);
            this.PasswordTextBox1.MaxLength = 32767;
            this.PasswordTextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.PasswordTextBox1.Modified = false;
            this.PasswordTextBox1.Multiline = false;
            this.PasswordTextBox1.Name = "PasswordTextBox1";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordTextBox1.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.PasswordTextBox1.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordTextBox1.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordTextBox1.OnIdleState = stateProperties16;
            this.PasswordTextBox1.Padding = new System.Windows.Forms.Padding(3);
            this.PasswordTextBox1.PasswordChar = '\0';
            this.PasswordTextBox1.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(31)))), ((int)(((byte)(74)))));
            this.PasswordTextBox1.PlaceholderText = "Enter your Password";
            this.PasswordTextBox1.ReadOnly = false;
            this.PasswordTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PasswordTextBox1.SelectedText = "";
            this.PasswordTextBox1.SelectionLength = 0;
            this.PasswordTextBox1.SelectionStart = 0;
            this.PasswordTextBox1.ShortcutsEnabled = true;
            this.PasswordTextBox1.Size = new System.Drawing.Size(341, 39);
            this.PasswordTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.PasswordTextBox1.TabIndex = 30;
            this.PasswordTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PasswordTextBox1.TextMarginBottom = 0;
            this.PasswordTextBox1.TextMarginLeft = 3;
            this.PasswordTextBox1.TextMarginTop = 1;
            this.PasswordTextBox1.TextPlaceholder = "Enter your Password";
            this.PasswordTextBox1.UseSystemPasswordChar = true;
            this.PasswordTextBox1.WordWrap = true;
            // 
            // Login
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(23)))), ((int)(((byte)(62)))));
            this.ClientSize = new System.Drawing.Size(636, 429);
            this.Controls.Add(this.PasswordTextBox1);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.ShowPassCheckBox);
            this.Controls.Add(this.bunifuPictureBox1);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuFormControlBox1);
            this.Controls.Add(this.showpasswordCheckBox);
            this.Controls.Add(this.PasswordTextBox);
            this.Controls.Add(this.LoginButton);
            this.Controls.Add(this.usernameTextBox);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.bunifuLabel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Login";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Login Form";
            this.Load += new System.EventHandler(this.Login_Load);
            this.bunifuPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuTextBox usernameTextBox;
        private Bunifu.UI.WinForms.BunifuTextBox PasswordTextBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton LoginButton;
        private Bunifu.UI.WinForms.BunifuCheckBox showpasswordCheckBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton RegisterButton;
        private Bunifu.UI.WinForms.BunifuFormControlBox bunifuFormControlBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuCheckBox ShowPassCheckBox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuTextBox PasswordTextBox1;
    }
}