namespace FreelancerApp
{
    partial class Register
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Register));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuFormControlBox1 = new Bunifu.UI.WinForms.BunifuFormControlBox();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.lastnameTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.RegisterButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.firstnameTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.EmailTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ConfirmPasswordTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.UsernameTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.PasswordTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.userTypeComboBox = new Bunifu.UI.WinForms.BunifuDropdown();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuFormControlBox1
            // 
            this.bunifuFormControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuFormControlBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(23)))), ((int)(((byte)(62)))));
            this.bunifuFormControlBox1.BunifuFormDrag = null;
            this.bunifuFormControlBox1.CloseBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.CloseBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.CloseBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.CloseBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.CloseBoxOptions.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.CloseBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.CloseBoxOptions.Icon")));
            this.bunifuFormControlBox1.CloseBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.CloseBoxOptions.IconColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.CloseBoxOptions.IconHoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.CloseBoxOptions.IconPressedColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.CloseBoxOptions.IconSize = new System.Drawing.Size(18, 18);
            this.bunifuFormControlBox1.CloseBoxOptions.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.HelpBox = false;
            this.bunifuFormControlBox1.HelpBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.HelpBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.HelpBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.HelpBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.HelpBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.HelpBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.HelpBoxOptions.Icon")));
            this.bunifuFormControlBox1.HelpBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.HelpBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconSize = new System.Drawing.Size(22, 22);
            this.bunifuFormControlBox1.HelpBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Location = new System.Drawing.Point(695, 0);
            this.bunifuFormControlBox1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuFormControlBox1.MaximizeBox = false;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconAlt = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.IconAlt")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconSize = new System.Drawing.Size(16, 16);
            this.bunifuFormControlBox1.MaximizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.MinimizeBox = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MinimizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconHoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconPressedColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconSize = new System.Drawing.Size(14, 14);
            this.bunifuFormControlBox1.MinimizeBoxOptions.PressedColor = System.Drawing.Color.DarkGray;
            this.bunifuFormControlBox1.Name = "bunifuFormControlBox1";
            this.bunifuFormControlBox1.ShowDesignBorders = false;
            this.bunifuFormControlBox1.Size = new System.Drawing.Size(105, 37);
            this.bunifuFormControlBox1.TabIndex = 10;
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = false;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = true;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = false;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("MV Boli", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(330, 127);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(99, 31);
            this.bunifuLabel1.TabIndex = 11;
            this.bunifuLabel1.Text = "Register";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lastnameTextBox
            // 
            this.lastnameTextBox.AcceptsReturn = false;
            this.lastnameTextBox.AcceptsTab = false;
            this.lastnameTextBox.AnimationSpeed = 200;
            this.lastnameTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.lastnameTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.lastnameTextBox.AutoSizeHeight = true;
            this.lastnameTextBox.BackColor = System.Drawing.Color.Transparent;
            this.lastnameTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("lastnameTextBox.BackgroundImage")));
            this.lastnameTextBox.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.lastnameTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.lastnameTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.lastnameTextBox.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            this.lastnameTextBox.BorderRadius = 15;
            this.lastnameTextBox.BorderThickness = 1;
            this.lastnameTextBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.lastnameTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.lastnameTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.lastnameTextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.lastnameTextBox.DefaultText = "";
            this.lastnameTextBox.FillColor = System.Drawing.Color.White;
            this.lastnameTextBox.HideSelection = true;
            this.lastnameTextBox.IconLeft = null;
            this.lastnameTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.lastnameTextBox.IconPadding = 10;
            this.lastnameTextBox.IconRight = null;
            this.lastnameTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.lastnameTextBox.Lines = new string[0];
            this.lastnameTextBox.Location = new System.Drawing.Point(380, 178);
            this.lastnameTextBox.MaxLength = 32767;
            this.lastnameTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.lastnameTextBox.Modified = false;
            this.lastnameTextBox.Multiline = false;
            this.lastnameTextBox.Name = "lastnameTextBox";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastnameTextBox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.lastnameTextBox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastnameTextBox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastnameTextBox.OnIdleState = stateProperties20;
            this.lastnameTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.lastnameTextBox.PasswordChar = '\0';
            this.lastnameTextBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(31)))), ((int)(((byte)(74)))));
            this.lastnameTextBox.PlaceholderText = "Enter your Second Name";
            this.lastnameTextBox.ReadOnly = false;
            this.lastnameTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.lastnameTextBox.SelectedText = "";
            this.lastnameTextBox.SelectionLength = 0;
            this.lastnameTextBox.SelectionStart = 0;
            this.lastnameTextBox.ShortcutsEnabled = true;
            this.lastnameTextBox.Size = new System.Drawing.Size(170, 39);
            this.lastnameTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.lastnameTextBox.TabIndex = 15;
            this.lastnameTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.lastnameTextBox.TextMarginBottom = 0;
            this.lastnameTextBox.TextMarginLeft = 3;
            this.lastnameTextBox.TextMarginTop = 1;
            this.lastnameTextBox.TextPlaceholder = "Enter your Second Name";
            this.lastnameTextBox.UseSystemPasswordChar = false;
            this.lastnameTextBox.WordWrap = true;
            // 
            // RegisterButton
            // 
            this.RegisterButton.AllowAnimations = true;
            this.RegisterButton.AllowMouseEffects = true;
            this.RegisterButton.AllowToggling = false;
            this.RegisterButton.AnimationSpeed = 200;
            this.RegisterButton.AutoGenerateColors = false;
            this.RegisterButton.AutoRoundBorders = false;
            this.RegisterButton.AutoSizeLeftIcon = true;
            this.RegisterButton.AutoSizeRightIcon = true;
            this.RegisterButton.BackColor = System.Drawing.Color.Transparent;
            this.RegisterButton.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.RegisterButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("RegisterButton.BackgroundImage")));
            this.RegisterButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegisterButton.ButtonText = "Sign Up";
            this.RegisterButton.ButtonTextMarginLeft = 0;
            this.RegisterButton.ColorContrastOnClick = 45;
            this.RegisterButton.ColorContrastOnHover = 45;
            this.RegisterButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.RegisterButton.CustomizableEdges = borderEdges1;
            this.RegisterButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.RegisterButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RegisterButton.DisabledFillColor = System.Drawing.Color.Empty;
            this.RegisterButton.DisabledForecolor = System.Drawing.Color.Empty;
            this.RegisterButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.RegisterButton.Font = new System.Drawing.Font("Segoe UI", 12.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.RegisterButton.ForeColor = System.Drawing.Color.White;
            this.RegisterButton.IconLeft = null;
            this.RegisterButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.RegisterButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.RegisterButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.RegisterButton.IconMarginLeft = 11;
            this.RegisterButton.IconPadding = 10;
            this.RegisterButton.IconRight = null;
            this.RegisterButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.RegisterButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.RegisterButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.RegisterButton.IconSize = 25;
            this.RegisterButton.IdleBorderColor = System.Drawing.Color.Empty;
            this.RegisterButton.IdleBorderRadius = 0;
            this.RegisterButton.IdleBorderThickness = 0;
            this.RegisterButton.IdleFillColor = System.Drawing.Color.Empty;
            this.RegisterButton.IdleIconLeftImage = null;
            this.RegisterButton.IdleIconRightImage = null;
            this.RegisterButton.IndicateFocus = false;
            this.RegisterButton.Location = new System.Drawing.Point(256, 496);
            this.RegisterButton.Name = "RegisterButton";
            this.RegisterButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.RegisterButton.OnDisabledState.BorderRadius = 15;
            this.RegisterButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegisterButton.OnDisabledState.BorderThickness = 1;
            this.RegisterButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.RegisterButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.RegisterButton.OnDisabledState.IconLeftImage = null;
            this.RegisterButton.OnDisabledState.IconRightImage = null;
            this.RegisterButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.RegisterButton.onHoverState.BorderRadius = 15;
            this.RegisterButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegisterButton.onHoverState.BorderThickness = 1;
            this.RegisterButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(62)))), ((int)(((byte)(120)))));
            this.RegisterButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.RegisterButton.onHoverState.IconLeftImage = null;
            this.RegisterButton.onHoverState.IconRightImage = null;
            this.RegisterButton.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.RegisterButton.OnIdleState.BorderRadius = 15;
            this.RegisterButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegisterButton.OnIdleState.BorderThickness = 1;
            this.RegisterButton.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(183)))), ((int)(((byte)(42)))));
            this.RegisterButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.RegisterButton.OnIdleState.IconLeftImage = null;
            this.RegisterButton.OnIdleState.IconRightImage = null;
            this.RegisterButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RegisterButton.OnPressedState.BorderRadius = 15;
            this.RegisterButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.RegisterButton.OnPressedState.BorderThickness = 1;
            this.RegisterButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.RegisterButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.RegisterButton.OnPressedState.IconLeftImage = null;
            this.RegisterButton.OnPressedState.IconRightImage = null;
            this.RegisterButton.Size = new System.Drawing.Size(234, 57);
            this.RegisterButton.TabIndex = 14;
            this.RegisterButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.RegisterButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.RegisterButton.TextMarginLeft = 0;
            this.RegisterButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.RegisterButton.UseDefaultRadiusAndThickness = true;
            this.RegisterButton.Click += new System.EventHandler(this.RegisterButton_Click);
            // 
            // firstnameTextBox
            // 
            this.firstnameTextBox.AcceptsReturn = false;
            this.firstnameTextBox.AcceptsTab = false;
            this.firstnameTextBox.AnimationSpeed = 200;
            this.firstnameTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.firstnameTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.firstnameTextBox.AutoSizeHeight = true;
            this.firstnameTextBox.BackColor = System.Drawing.Color.Transparent;
            this.firstnameTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("firstnameTextBox.BackgroundImage")));
            this.firstnameTextBox.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.firstnameTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.firstnameTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.firstnameTextBox.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            this.firstnameTextBox.BorderRadius = 15;
            this.firstnameTextBox.BorderThickness = 1;
            this.firstnameTextBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.firstnameTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.firstnameTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.firstnameTextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.firstnameTextBox.DefaultText = "";
            this.firstnameTextBox.FillColor = System.Drawing.Color.White;
            this.firstnameTextBox.HideSelection = true;
            this.firstnameTextBox.IconLeft = null;
            this.firstnameTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.firstnameTextBox.IconPadding = 10;
            this.firstnameTextBox.IconRight = null;
            this.firstnameTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.firstnameTextBox.Lines = new string[0];
            this.firstnameTextBox.Location = new System.Drawing.Point(209, 178);
            this.firstnameTextBox.MaxLength = 32767;
            this.firstnameTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.firstnameTextBox.Modified = false;
            this.firstnameTextBox.Multiline = false;
            this.firstnameTextBox.Name = "firstnameTextBox";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstnameTextBox.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.firstnameTextBox.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstnameTextBox.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstnameTextBox.OnIdleState = stateProperties24;
            this.firstnameTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.firstnameTextBox.PasswordChar = '\0';
            this.firstnameTextBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(31)))), ((int)(((byte)(74)))));
            this.firstnameTextBox.PlaceholderText = "Enter your First Name";
            this.firstnameTextBox.ReadOnly = false;
            this.firstnameTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.firstnameTextBox.SelectedText = "";
            this.firstnameTextBox.SelectionLength = 0;
            this.firstnameTextBox.SelectionStart = 0;
            this.firstnameTextBox.ShortcutsEnabled = true;
            this.firstnameTextBox.Size = new System.Drawing.Size(165, 39);
            this.firstnameTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.firstnameTextBox.TabIndex = 13;
            this.firstnameTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.firstnameTextBox.TextMarginBottom = 0;
            this.firstnameTextBox.TextMarginLeft = 3;
            this.firstnameTextBox.TextMarginTop = 1;
            this.firstnameTextBox.TextPlaceholder = "Enter your First Name";
            this.firstnameTextBox.UseSystemPasswordChar = false;
            this.firstnameTextBox.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.AutoSize = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Baskerville Old Face", 26.25F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel4.Location = new System.Drawing.Point(307, 75);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(174, 46);
            this.bunifuLabel4.TabIndex = 18;
            this.bunifuLabel4.Text = "Freelancer";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // EmailTextBox
            // 
            this.EmailTextBox.AcceptsReturn = false;
            this.EmailTextBox.AcceptsTab = false;
            this.EmailTextBox.AnimationSpeed = 200;
            this.EmailTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.EmailTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.EmailTextBox.AutoSizeHeight = true;
            this.EmailTextBox.BackColor = System.Drawing.Color.Transparent;
            this.EmailTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("EmailTextBox.BackgroundImage")));
            this.EmailTextBox.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.EmailTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.EmailTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.EmailTextBox.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            this.EmailTextBox.BorderRadius = 15;
            this.EmailTextBox.BorderThickness = 1;
            this.EmailTextBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.EmailTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.EmailTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.EmailTextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.EmailTextBox.DefaultText = "";
            this.EmailTextBox.FillColor = System.Drawing.Color.White;
            this.EmailTextBox.HideSelection = true;
            this.EmailTextBox.IconLeft = null;
            this.EmailTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.EmailTextBox.IconPadding = 10;
            this.EmailTextBox.IconRight = null;
            this.EmailTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.EmailTextBox.Lines = new string[0];
            this.EmailTextBox.Location = new System.Drawing.Point(209, 223);
            this.EmailTextBox.MaxLength = 32767;
            this.EmailTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.EmailTextBox.Modified = false;
            this.EmailTextBox.Multiline = false;
            this.EmailTextBox.Name = "EmailTextBox";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmailTextBox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.EmailTextBox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmailTextBox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.EmailTextBox.OnIdleState = stateProperties16;
            this.EmailTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.EmailTextBox.PasswordChar = '\0';
            this.EmailTextBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(31)))), ((int)(((byte)(74)))));
            this.EmailTextBox.PlaceholderText = "Enter your Email Address";
            this.EmailTextBox.ReadOnly = false;
            this.EmailTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.EmailTextBox.SelectedText = "";
            this.EmailTextBox.SelectionLength = 0;
            this.EmailTextBox.SelectionStart = 0;
            this.EmailTextBox.ShortcutsEnabled = true;
            this.EmailTextBox.Size = new System.Drawing.Size(341, 39);
            this.EmailTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.EmailTextBox.TabIndex = 19;
            this.EmailTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.EmailTextBox.TextMarginBottom = 0;
            this.EmailTextBox.TextMarginLeft = 3;
            this.EmailTextBox.TextMarginTop = 1;
            this.EmailTextBox.TextPlaceholder = "Enter your Email Address";
            this.EmailTextBox.UseSystemPasswordChar = false;
            this.EmailTextBox.WordWrap = true;
            // 
            // ConfirmPasswordTextBox
            // 
            this.ConfirmPasswordTextBox.AcceptsReturn = false;
            this.ConfirmPasswordTextBox.AcceptsTab = false;
            this.ConfirmPasswordTextBox.AnimationSpeed = 200;
            this.ConfirmPasswordTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ConfirmPasswordTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ConfirmPasswordTextBox.AutoSizeHeight = true;
            this.ConfirmPasswordTextBox.BackColor = System.Drawing.Color.Transparent;
            this.ConfirmPasswordTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ConfirmPasswordTextBox.BackgroundImage")));
            this.ConfirmPasswordTextBox.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.ConfirmPasswordTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ConfirmPasswordTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.ConfirmPasswordTextBox.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            this.ConfirmPasswordTextBox.BorderRadius = 15;
            this.ConfirmPasswordTextBox.BorderThickness = 1;
            this.ConfirmPasswordTextBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.ConfirmPasswordTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ConfirmPasswordTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ConfirmPasswordTextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.ConfirmPasswordTextBox.DefaultText = "";
            this.ConfirmPasswordTextBox.FillColor = System.Drawing.Color.White;
            this.ConfirmPasswordTextBox.HideSelection = true;
            this.ConfirmPasswordTextBox.IconLeft = null;
            this.ConfirmPasswordTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ConfirmPasswordTextBox.IconPadding = 10;
            this.ConfirmPasswordTextBox.IconRight = null;
            this.ConfirmPasswordTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ConfirmPasswordTextBox.Lines = new string[0];
            this.ConfirmPasswordTextBox.Location = new System.Drawing.Point(209, 358);
            this.ConfirmPasswordTextBox.MaxLength = 32767;
            this.ConfirmPasswordTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.ConfirmPasswordTextBox.Modified = false;
            this.ConfirmPasswordTextBox.Multiline = false;
            this.ConfirmPasswordTextBox.Name = "ConfirmPasswordTextBox";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ConfirmPasswordTextBox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ConfirmPasswordTextBox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ConfirmPasswordTextBox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ConfirmPasswordTextBox.OnIdleState = stateProperties12;
            this.ConfirmPasswordTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.ConfirmPasswordTextBox.PasswordChar = '\0';
            this.ConfirmPasswordTextBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(31)))), ((int)(((byte)(74)))));
            this.ConfirmPasswordTextBox.PlaceholderText = "Confirm Password";
            this.ConfirmPasswordTextBox.ReadOnly = false;
            this.ConfirmPasswordTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ConfirmPasswordTextBox.SelectedText = "";
            this.ConfirmPasswordTextBox.SelectionLength = 0;
            this.ConfirmPasswordTextBox.SelectionStart = 0;
            this.ConfirmPasswordTextBox.ShortcutsEnabled = true;
            this.ConfirmPasswordTextBox.Size = new System.Drawing.Size(341, 39);
            this.ConfirmPasswordTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ConfirmPasswordTextBox.TabIndex = 20;
            this.ConfirmPasswordTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ConfirmPasswordTextBox.TextMarginBottom = 0;
            this.ConfirmPasswordTextBox.TextMarginLeft = 3;
            this.ConfirmPasswordTextBox.TextMarginTop = 1;
            this.ConfirmPasswordTextBox.TextPlaceholder = "Confirm Password";
            this.ConfirmPasswordTextBox.UseSystemPasswordChar = true;
            this.ConfirmPasswordTextBox.WordWrap = true;
            // 
            // UsernameTextBox
            // 
            this.UsernameTextBox.AcceptsReturn = false;
            this.UsernameTextBox.AcceptsTab = false;
            this.UsernameTextBox.AnimationSpeed = 200;
            this.UsernameTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.UsernameTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.UsernameTextBox.AutoSizeHeight = true;
            this.UsernameTextBox.BackColor = System.Drawing.Color.Transparent;
            this.UsernameTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("UsernameTextBox.BackgroundImage")));
            this.UsernameTextBox.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.UsernameTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UsernameTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.UsernameTextBox.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            this.UsernameTextBox.BorderRadius = 15;
            this.UsernameTextBox.BorderThickness = 1;
            this.UsernameTextBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.UsernameTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.UsernameTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.UsernameTextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.UsernameTextBox.DefaultText = "";
            this.UsernameTextBox.FillColor = System.Drawing.Color.White;
            this.UsernameTextBox.HideSelection = true;
            this.UsernameTextBox.IconLeft = null;
            this.UsernameTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.UsernameTextBox.IconPadding = 10;
            this.UsernameTextBox.IconRight = null;
            this.UsernameTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.UsernameTextBox.Lines = new string[0];
            this.UsernameTextBox.Location = new System.Drawing.Point(209, 268);
            this.UsernameTextBox.MaxLength = 32767;
            this.UsernameTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.UsernameTextBox.Modified = false;
            this.UsernameTextBox.Multiline = false;
            this.UsernameTextBox.Name = "UsernameTextBox";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UsernameTextBox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.UsernameTextBox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UsernameTextBox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UsernameTextBox.OnIdleState = stateProperties8;
            this.UsernameTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.UsernameTextBox.PasswordChar = '\0';
            this.UsernameTextBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(31)))), ((int)(((byte)(74)))));
            this.UsernameTextBox.PlaceholderText = "Enter your Username";
            this.UsernameTextBox.ReadOnly = false;
            this.UsernameTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.UsernameTextBox.SelectedText = "";
            this.UsernameTextBox.SelectionLength = 0;
            this.UsernameTextBox.SelectionStart = 0;
            this.UsernameTextBox.ShortcutsEnabled = true;
            this.UsernameTextBox.Size = new System.Drawing.Size(341, 39);
            this.UsernameTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.UsernameTextBox.TabIndex = 21;
            this.UsernameTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.UsernameTextBox.TextMarginBottom = 0;
            this.UsernameTextBox.TextMarginLeft = 3;
            this.UsernameTextBox.TextMarginTop = 1;
            this.UsernameTextBox.TextPlaceholder = "Enter your Username";
            this.UsernameTextBox.UseSystemPasswordChar = false;
            this.UsernameTextBox.WordWrap = true;
            // 
            // PasswordTextBox
            // 
            this.PasswordTextBox.AcceptsReturn = false;
            this.PasswordTextBox.AcceptsTab = false;
            this.PasswordTextBox.AnimationSpeed = 200;
            this.PasswordTextBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PasswordTextBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PasswordTextBox.AutoSizeHeight = true;
            this.PasswordTextBox.BackColor = System.Drawing.Color.Transparent;
            this.PasswordTextBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PasswordTextBox.BackgroundImage")));
            this.PasswordTextBox.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.PasswordTextBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PasswordTextBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            this.PasswordTextBox.BorderColorIdle = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            this.PasswordTextBox.BorderRadius = 15;
            this.PasswordTextBox.BorderThickness = 1;
            this.PasswordTextBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.PasswordTextBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PasswordTextBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PasswordTextBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.PasswordTextBox.DefaultText = "";
            this.PasswordTextBox.FillColor = System.Drawing.Color.White;
            this.PasswordTextBox.HideSelection = true;
            this.PasswordTextBox.IconLeft = null;
            this.PasswordTextBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.PasswordTextBox.IconPadding = 10;
            this.PasswordTextBox.IconRight = null;
            this.PasswordTextBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.PasswordTextBox.Lines = new string[0];
            this.PasswordTextBox.Location = new System.Drawing.Point(209, 313);
            this.PasswordTextBox.MaxLength = 32767;
            this.PasswordTextBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.PasswordTextBox.Modified = false;
            this.PasswordTextBox.Multiline = false;
            this.PasswordTextBox.Name = "PasswordTextBox";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordTextBox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.PasswordTextBox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(60)))), ((int)(((byte)(120)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordTextBox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(14)))), ((int)(((byte)(20)))), ((int)(((byte)(54)))));
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PasswordTextBox.OnIdleState = stateProperties4;
            this.PasswordTextBox.Padding = new System.Windows.Forms.Padding(3);
            this.PasswordTextBox.PasswordChar = '\0';
            this.PasswordTextBox.PlaceholderForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(31)))), ((int)(((byte)(74)))));
            this.PasswordTextBox.PlaceholderText = "Enter your Password";
            this.PasswordTextBox.ReadOnly = false;
            this.PasswordTextBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PasswordTextBox.SelectedText = "";
            this.PasswordTextBox.SelectionLength = 0;
            this.PasswordTextBox.SelectionStart = 0;
            this.PasswordTextBox.ShortcutsEnabled = true;
            this.PasswordTextBox.Size = new System.Drawing.Size(341, 39);
            this.PasswordTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.PasswordTextBox.TabIndex = 22;
            this.PasswordTextBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PasswordTextBox.TextMarginBottom = 0;
            this.PasswordTextBox.TextMarginLeft = 3;
            this.PasswordTextBox.TextMarginTop = 1;
            this.PasswordTextBox.TextPlaceholder = "Enter your Password";
            this.PasswordTextBox.UseSystemPasswordChar = true;
            this.PasswordTextBox.WordWrap = true;
            // 
            // userTypeComboBox
            // 
            this.userTypeComboBox.BackColor = System.Drawing.Color.Transparent;
            this.userTypeComboBox.BackgroundColor = System.Drawing.Color.White;
            this.userTypeComboBox.BorderColor = System.Drawing.Color.Silver;
            this.userTypeComboBox.BorderRadius = 1;
            this.userTypeComboBox.Color = System.Drawing.Color.Silver;
            this.userTypeComboBox.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.userTypeComboBox.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.userTypeComboBox.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.userTypeComboBox.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.userTypeComboBox.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.userTypeComboBox.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.userTypeComboBox.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.userTypeComboBox.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.userTypeComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.userTypeComboBox.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.userTypeComboBox.FillDropDown = true;
            this.userTypeComboBox.FillIndicator = false;
            this.userTypeComboBox.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.userTypeComboBox.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.userTypeComboBox.ForeColor = System.Drawing.Color.Black;
            this.userTypeComboBox.FormattingEnabled = true;
            this.userTypeComboBox.Icon = null;
            this.userTypeComboBox.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.userTypeComboBox.IndicatorColor = System.Drawing.Color.DarkGray;
            this.userTypeComboBox.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.userTypeComboBox.IndicatorThickness = 2;
            this.userTypeComboBox.IsDropdownOpened = false;
            this.userTypeComboBox.ItemBackColor = System.Drawing.Color.White;
            this.userTypeComboBox.ItemBorderColor = System.Drawing.Color.White;
            this.userTypeComboBox.ItemForeColor = System.Drawing.Color.Black;
            this.userTypeComboBox.ItemHeight = 26;
            this.userTypeComboBox.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.userTypeComboBox.ItemHighLightForeColor = System.Drawing.Color.White;
            this.userTypeComboBox.ItemTopMargin = 3;
            this.userTypeComboBox.Location = new System.Drawing.Point(209, 439);
            this.userTypeComboBox.Name = "userTypeComboBox";
            this.userTypeComboBox.Size = new System.Drawing.Size(341, 32);
            this.userTypeComboBox.TabIndex = 23;
            this.userTypeComboBox.Text = null;
            this.userTypeComboBox.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.userTypeComboBox.TextLeftMargin = 5;
            this.userTypeComboBox.SelectedIndexChanged += new System.EventHandler(this.userTypeComboBox_SelectedIndexChanged);
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.AutoSize = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Ebrima", 17F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel3.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel3.Location = new System.Drawing.Point(209, 401);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(127, 32);
            this.bunifuLabel3.TabIndex = 24;
            this.bunifuLabel3.Text = "User Type";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = false;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(350, 0);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(79, 79);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 28;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // Register
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(18)))), ((int)(((byte)(23)))), ((int)(((byte)(62)))));
            this.ClientSize = new System.Drawing.Size(800, 576);
            this.Controls.Add(this.bunifuPictureBox1);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.userTypeComboBox);
            this.Controls.Add(this.PasswordTextBox);
            this.Controls.Add(this.UsernameTextBox);
            this.Controls.Add(this.ConfirmPasswordTextBox);
            this.Controls.Add(this.EmailTextBox);
            this.Controls.Add(this.bunifuFormControlBox1);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.lastnameTextBox);
            this.Controls.Add(this.RegisterButton);
            this.Controls.Add(this.firstnameTextBox);
            this.Controls.Add(this.bunifuLabel4);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Register";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Register";
            this.Load += new System.EventHandler(this.Register_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuFormControlBox bunifuFormControlBox1;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuTextBox lastnameTextBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton RegisterButton;
        private Bunifu.UI.WinForms.BunifuTextBox firstnameTextBox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuDropdown userTypeComboBox;
        private Bunifu.UI.WinForms.BunifuTextBox PasswordTextBox;
        private Bunifu.UI.WinForms.BunifuTextBox UsernameTextBox;
        private Bunifu.UI.WinForms.BunifuTextBox ConfirmPasswordTextBox;
        private Bunifu.UI.WinForms.BunifuTextBox EmailTextBox;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
    }
}